# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ably' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ably
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'Alamofire', '~> 5.1'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SwipeMenuViewController'
  pod 'PMSuperButton'

  target 'AblyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AblyUITests' do
    # Pods for testing
  end

end
